plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - usage/basics.md
  - usage/multipleplots.md
  - internals/structure.md
  - internals/createplots.md
  - internals/drawplots.md
  - internals/extending.md

theme: jekyll-theme-slate
